# Generated by Django 5.2.3 on 2025-06-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='middleName',
            new_name='middlename',
        ),
    ]
