# Generated by Django 5.2.3 on 2025-06-14 08:26

import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_filestore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestore',
            name='document',
            field=models.FileField(null=True, upload_to=posts.models.user_directory_path),
        ),
        migrations.CreateModel(
            name='UserResponds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variants', models.ManyToManyField(to='posts.answervariant')),
            ],
        ),
    ]
