# Generated by Django 5.2.3 on 2025-06-14 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_filestore_document_userresponds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponds',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userresponds',
            name='variants',
        ),
        migrations.AddField(
            model_name='userresponds',
            name='variants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.answervariant'),
        ),
    ]
