# Generated by Django 5.2.3 on 2025-06-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_userresponds_user_remove_userresponds_variants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponds',
            old_name='variants',
            new_name='variant',
        ),
    ]
