# Generated by Django 5.2.3 on 2025-06-14 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_variants_userresponds_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponds',
            name='user',
        ),
        migrations.CreateModel(
            name='UserRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userresponds',
            name='userrequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.userrequests'),
        ),
    ]
