# Generated by Django 5.2.3 on 2025-06-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_userresponds_user_userrequests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answervariant',
            name='point',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
