# Generated by Django 5.2.3 on 2025-06-14 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_answervariant_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequests',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.filestore'),
        ),
        migrations.AddField(
            model_name='userrequests',
            name='status',
            field=models.CharField(default='На рассмотрении'),
        ),
    ]
