# Generated by Django 5.2.3 on 2025-06-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_userrequests_file_userrequests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Student', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
