# Generated by Django 5.2.3 on 2025-06-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_user_role_alter_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestore',
            name='filename',
            field=models.CharField(default='Stub', null=True),
        ),
    ]
