# Generated by Django 5.2.3 on 2025-06-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_filestore_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='application_id',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='declaration_id',
            field=models.SmallIntegerField(null=True),
        ),
    ]
