# Generated by Django 5.2.3 on 2025-06-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_user_application_id_user_declaration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequests',
            name='name',
            field=models.CharField(default='unnamed'),
        ),
    ]
