# Generated by Django 5.2.3 on 2025-06-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_userrequests_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequests',
            name='comment',
            field=models.CharField(null=True),
        ),
    ]
