# Generated by Django 5.2.3 on 2025-06-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_userrequests_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequests',
            name='name',
            field=models.CharField(default='Unnamed'),
        ),
    ]
